In [1]:
import numpy as np
import tensorflow as tf

In [8]:
class DeepNN:
    def __init__(self, layers_dim: tuple[int], learning_rate: float = 0.09):
        self.params = self.init_params(layers_dim)
        self.layers_dim = layers_dim

    def init_params(self, layers_dim):
        tf.random.set_seed(42)
        params = dict()
        for l in range(1, len(layers_dim)):
            params['W' + str(l)] = tf.random.normal([layers_dim[l],
                                                     layers_dim[l-1]]) * 0.01
            params['b' + str(l)] = tf.random.normal([layers_dim[l], 1])
        return params

    def forward(self, A: tf.Tensor, W: tf.Tensor, b: tf.Tendor):
        Z = tf.tensordot(tf.transpose(W), A) + b
        state = (A, W, b)
        return Z, state

    def Layer_forward(self, A: tf.Tensor):
        activation = "relu"
        states = []
        for l in range(1, len(self.layers_dim)):
            if activation == "sigmoid":
                Z, state = self.forward(A, self.params['W'+str(l)], self.params['W'+str(l)])
                A = tf.nn.sigmoid(Z)
            if activation == 'relu':
                Z, state = self.forward(A, self.params['W'+str(l)], self.params['W'+str(l)])
                A = tf.nn.relu(Z)
        return 


In [17]:
nn = DeepNN(layers_dim=(4,5,3,1))
nn.params

{'W1': <tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.00327469, -0.00842626,  0.00319434, -0.01407552],
        [-0.0238806 , -0.01039248, -0.00557323,  0.00539707],
        [ 0.01699432,  0.00288937, -0.01506612, -0.00264547],
        [-0.00597224, -0.01917113, -0.00620441,  0.00850402],
        [-0.00406048, -0.03025841,  0.00905846,  0.0029856 ]],
       dtype=float32)>,
 'b1': <tf.Tensor: shape=(5, 1), dtype=float32, numpy=
 array([[ 0.08422458],
        [-0.86090374],
        [ 0.37812304],
        [-0.00519627],
        [-0.49453196]], dtype=float32)>,
 'W2': <tf.Tensor: shape=(3, 5), dtype=float32, numpy=
 array([[-0.00559097, -0.00534721,  0.02373033, -0.01572593,  0.00805506],
        [-0.00833877,  0.00306112,  0.02266049,  0.00285641, -0.01553616],
        [ 0.00379755,  0.00766463,  0.00361148,  0.00096533,  0.00216956]],
       dtype=float32)>,
 'b2': <tf.Tensor: shape=(3, 1), dtype=float32, numpy=
 array([[ 0.65648675],
        [-0.4130517 ],
        [ 0.3399